version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6
  node: circleci/node@1.1.6
workflows:
  build-test-report:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
      - report:
          requires:
            - test

jobs:
  build:
    docker:
      - image: circleci/node:10.18.0
    working_directory: ~/tradingvenue
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install packages
          command: npm install
      - run:
          name: Build Contracts and types
          command: npm run build
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
            - build
            - typechain
  
  lint:
    docker:
      - image: circleci/node:10.18.0
    working_directory: ~/tradingvenue
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Lint Contracts
          command: npm run lint:sol
      - run:
          name: Lint typescript
          command: npm run lint:ts
  
  test:
    working_directory: ~/tradingvenue
    docker:
      - image: circleci/node:10.18.0
      - image: trufflesuite/ganache-cli:v6.9.1
        command: ganache-cli --deterministic -e 300 -p 8545 -m 'candy maple cake sugar pudding cream honey rich smooth crumble sweet treat' --accounts 30 --allowUnlimitedContractSize
    
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Build Contracts and types
          command: npm run build
      - run:
          name: Test Contracts
          command: npm run test
  
  report:
    docker:
      - image: circleci/node:10.18.0
    working_directory: ~/tradingvenue
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: 
          name: Gas Reporter
          command: npx codechecks
      - run:
          name: Produce Coverage Report
          command: npm run coverage
      # - coveralls/upload:
      #     path_to_lcov: ./coverage/lcov.info
      - store_artifacts:
          path: /coverage
      - store_artifacts:
          path: /coverage.json
      - store_artifacts:
          path: test-results.xml